### ISSUE TITLE
Colors are not consistent with the vscode dark+ color scheme for Python

### ISSUE THREAD

**Issue by AMER12-max** [ianpan870102/vscode-default-dark-emacs-theme#12]
Hi, I just want to say that I love this colorscheme and it is the closest version I could find to vscode's dark+ colorscheme. 

I found some minor mistakes with the syntax highlighting when it comes to Python. 

This is the way which _super()_ is colored in your version of vscode's dark+:

![image](https://user-images.githubusercontent.com/58982077/110246525-d78e9b00-7f5f-11eb-88a1-1df4d447688d.png)

This is the way which _super()_ is colored in vscode:

![image](https://user-images.githubusercontent.com/58982077/110246575-0a389380-7f60-11eb-8a4d-2b3fcf1821b3.png)

This is the way the function _hasattr()_ is colored in your version of vscode's dark+:

![image](https://user-images.githubusercontent.com/58982077/110246648-508df280-7f60-11eb-98b6-d7ef0cc901da.png)

This is the way the function _hasattr()_ is colored in vscode:

![image](https://user-images.githubusercontent.com/58982077/110246664-656a8600-7f60-11eb-93b7-cad8ce361df2.png)

This is the way parameters are colored in your version of vscode's dark+:

![image](https://user-images.githubusercontent.com/58982077/110246695-8fbc4380-7f60-11eb-9a99-aea13584452c.png)

This is the way parameters are colored in vscode:

![image](https://user-images.githubusercontent.com/58982077/110246727-a6fb3100-7f60-11eb-8abb-d36e214aeaeb.png)

**Comment by ianyepan** [comment]
Thanks for opening the issue. This very problem has also come to my attention while I was creating this theme. 

Unfortunately, this is due to the fundamental differences in how Emacs and Visual Studio Code parse code syntax and apply the colors.
For instance, both `super()` and `hasattr()` are simply interpreted as function calls in Emacs. Whereas in VSCode, the editor has the ability to give `super()`, `__init__()` and `hasattr()` 3 different colors because it understands their significance within context. Microsoft has put in quite some work to perfect the syntax highlighting sophistication and experience for VScode, which frankly, Emacs just doesn't have. (Although sometimes Emacs seems to have the upper hand, for example, it recognizes `self` as a legit keyword). On top of that, Emacs sometimes have inconsistencies of keyword colorings between different languages that are sadly not solvable at a theme-level.

That said, I've tried my best to look at different languages and pick the right color for "the most" use cases for each keyword. I do hope you continue to enjoy using this theme!

**Comment by AMER12-max** [comment]
Thanks for answering. I guess you tried your best since this is limitation with emacs itself. I guess we can close the issue now.

**Comment by ianyepan** [comment]
@AMER12-max  Traditionally Emacs uses regex for syntax parsing and highlighting (which is rather primitive). If you want a more modern and intelligent, you might wanna look into tree-sitter (it's quite amazing for syntax highlighting at least): https://ubolonton.github.io/emacs-tree-sitter/syntax-highlighting/
