### ISSUE TITLE
org-columns is off

### ISSUE THREAD

**Issue by shukryzablah** [ianpan870102/vscode-default-dark-emacs-theme#9]
Take this example text in an org file: 

```
* Top Goals [1/2]
** TODO this is the first task
** DONE this is another task
```

When calling `org-columns` for the whole buffer (no customizations), columns are off due to boxes in the todo and tags columns.

**Comment by ianyepan** [comment]
Thanks for bringing that up. Yes, this is one downside of using boxes around certain texts in Emacs. As far as I know, we can't avoid having a slightly increased width due to the box's borders.
If you prefer to **not** have the boxes around those TODO keywords, you can manually disable them through a custom set-face-attribute, or use the :custom-face keyword if you're on use-package
